[account]
email_address = ""
password = ""
# watch_spam = false
# show_name = false
# show_subject = false
# show_body = false

[gotify]
url = ""
token = ""
# format = "New Mail from {{name}} <{{address}}>: {{subject}}\n{{body}}"
